CREATE TABLE "users" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"email" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"username" VARCHAR(50) NOT NULL,
	"picture" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "sessions" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "likes" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"postId" INTEGER NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "urls" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"url" TEXT NOT NULL UNIQUE,
	"title" TEXT NOT NULL,
	"image" TEXT NOT NULL,
	"description" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "hashtags" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"hashtag" TEXT NOT NULL UNIQUE,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "posts" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"userId" INTEGER NOT NULL,
	"urlId" INTEGER NOT NULL,
	"text" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "postsHashtags" (
	"id" SERIAL NOT NULL PRIMARY KEY PRIMARY KEY,
	"postId" INTEGER NOT NULL,
	"hashtagId" INTEGER NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "shares" (
	"id" SERIAL NOT NULL PRIMARY KEY,
	"postId" INTEGER NOT NULL,
	"userId" INTEGER NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "followers" (
	"id" SERIAL NOT NULL PRIMARY KEY,
	"followedId" INTEGER NOT NULL,
	"followerId" INTEGER NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "comments" (
	"id" SERIAL NOT NULL PRIMARY KEY,
	"postId" INTEGER NOT NULL,
	"userId" INTEGER NOT NULL,
	"comment" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE "sessions" ADD CONSTRAINT "sessions_fk0" FOREIGN KEY ("userId") REFERENCES "users"("id");

ALTER TABLE "likes" ADD CONSTRAINT "likes_fk0" FOREIGN KEY ("userId") REFERENCES "users"("id");
ALTER TABLE "likes" ADD CONSTRAINT "likes_fk1" FOREIGN KEY ("postId") REFERENCES "posts"("id");

ALTER TABLE "posts" ADD CONSTRAINT "posts_fk0" FOREIGN KEY ("userid") REFERENCES "users"("id");
ALTER TABLE "posts" ADD CONSTRAINT "posts_fk1" FOREIGN KEY ("linkId") REFERENCES "urls"("id");

ALTER TABLE "postsHashtags" ADD CONSTRAINT "postsHashtags_fk0" FOREIGN KEY ("postId") REFERENCES "posts"("id");
ALTER TABLE "postsHashtags" ADD CONSTRAINT "postsHashtags_fk1" FOREIGN KEY ("hashtagId") REFERENCES "hashtags"("id");

ALTER TABLE "shares" ADD CONSTRAINT "shares_fk0" FOREIGN KEY ("postId") REFERENCES "posts"("id");
ALTER TABLE "shares" ADD CONSTRAINT "shares_fk1" FOREIGN KEY ("userId") REFERENCES "users"("id");

ALTER TABLE "followers" ADD CONSTRAINT "followers_fk0" FOREIGN KEY ("followedId") REFERENCES "users"("id");
ALTER TABLE "followers" ADD CONSTRAINT "followers_fk1" FOREIGN KEY ("followerId") REFERENCES "users"("id");

ALTER TABLE "comments" ADD CONSTRAINT "comments_fk0" FOREIGN KEY ("postId") REFERENCES "posts"("id");
ALTER TABLE "comments" ADD CONSTRAINT "comments_fk1" FOREIGN KEY ("userId") REFERENCES "users"("id");